apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "example-webhook.doslab.io"
webhooks:
- name: "example-webhook.doslab.io"
  objectSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - example
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1UQXhNREE0TlRFd05sb1hEVE14TVRBd09EQTROVEV3Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS1FVCkZHbGRLRWlRQlpRSmZoZXZLem9wNlRzL0g1bytGbUVxOHdqWXpqNm43ZW84WVVCR3hlTlNseVlZZFRZcG1vMHEKQnhvUklOc2VxSFdqejducEp6bGhFeDUwQkxRL3dUaFRiMjhuNHZweEFSOThqWU5nM2lNTEd4S0FnUEdYUm11awo4TlFwK1h3OG5tZm5FejBGenhTRDBhMGxER0piUnFPdUQzYlpCdEJaTHBiTzBVUGM2VHRuKzJwSURnelJCUlByCmxjKys0Q1pkZG1hd1ZDakQ4RW1QS3NLY0dFMmVVTlJuN1hMaDQyKzZCa0JBSDRaT01xTUlZWkdQOTZqaWJXbkwKdjhsVVV5eFVUdVhGV28xNWhMVkpYUlVrbWQzeGsvVWpxdkdvSnRTTFBWbHNNeWdnT3pIT1BJK3FvVVBscDNEcApNb3Noam8xK1FOem1CWkdWV2djQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCTjEyMVlHOGorSGpBM2hjMFhSYnZpdklHZXhNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCUjYxeUdKZlZIQ2hZaWk5NUgxV1U5ZVlEVHJzbTRoYk5sRy9XYzdYRm15UUVkaS9TVApocDZ4eVN0cGhyMFhaTWF3WFkzRDNWWHcxT3VZSUo3cVNxMFg1REhSby9FQ1MwZzR1UEUyQ0Z1bGVFNXRTZkNyCnljWnNpVFE2NHl4MlAwelQyUTJDTDlzUCtEMzlrWlZCdm9FZ0ZKZjQxd0cxNDhhQmZDVER1b0tQdWFoeStvMXUKQ3BLUjByWWtJRVZZQ3ZBQmF1TUtQZUxySVhGb2s0ai9vOHM4cVZXL3d2dGw4YWFTMFZOR1owVDdlenJPVWlnbQpYcG9Kb1hZNlVhOEh2R1BMV1A5RGFlMWs5S2NDVXQwVjhqMTFTL1VCZHdxNElyMkUwVVRIN1hSeTRJMndtUVNwCjRPMHBaVE9PN3J3bjdTbklHRElnVEwyNVA1c3JOSUh6TkhpdQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    url: <ip>:<port>/<path>
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 10
