apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: example-mutating-webhook
  namespace: kube-system
webhooks:
  - name: mutating.example.com
    clientConfig:
      service:
        name: webhook-service
        namespace: default
        path: /mutate
      serviceAccountName: kubernetes-client
    admissionReviewVersions:
      - v1
      - v1beta1
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
    failurePolicy: Fail
    sideEffects: None
    namespaceSelector:
      matchExpressions:
        - key: example.com/mutate
          operator: In
          values:
            - "true"